/**
 * The home page's behind-the-head animation set — Noah's paper cut-outs,
 * re-photographed frame by frame.
 *
 * GENERATED by tools/behind-head/build_behind.py — do not edit by hand.
 * Re-run that script when the source PSDs change; the sizes here are each
 * set's real pixel dimensions after frame registration, which BehindHead
 * uses for aspect ratios.
 *
 * 2026-08-23, Noah: "Furthest back is a red star, then a yellow star, then
 * my head, then the blue star, then the pencil marks."
 */

export type BehindSet = {
  /** Frame image paths, in order, starting at frame 1. */
  frames: string[];
  /** Registered canvas size, shared by every frame in the set. */
  width: number;
  height: number;
};

export type PencilMark = { src: string; width: number; height: number };


export const BEHIND_SETS: Record<string, BehindSet> = {
  yellow: {
    frames: ["/assets/home/behind-head/yellow/1.webp", "/assets/home/behind-head/yellow/2.webp", "/assets/home/behind-head/yellow/3.webp", "/assets/home/behind-head/yellow/4.webp", "/assets/home/behind-head/yellow/5.webp", "/assets/home/behind-head/yellow/6.webp", "/assets/home/behind-head/yellow/7.webp", "/assets/home/behind-head/yellow/8.webp"],
    width: 1000,
    height: 1000,
  },
  red: {
    frames: ["/assets/home/behind-head/red/1.webp", "/assets/home/behind-head/red/2.webp", "/assets/home/behind-head/red/3.webp", "/assets/home/behind-head/red/4.webp", "/assets/home/behind-head/red/5.webp"],
    width: 720,
    height: 745,
  },
  blue: {
    frames: ["/assets/home/behind-head/blue/1.webp", "/assets/home/behind-head/blue/2.webp", "/assets/home/behind-head/blue/3.webp", "/assets/home/behind-head/blue/4.webp", "/assets/home/behind-head/blue/5.webp", "/assets/home/behind-head/blue/6.webp"],
    width: 820,
    height: 761,
  },
};

export const PENCIL_MARKS: PencilMark[] = [
  { src: "/assets/home/behind-head/pencil/1.webp", width: 460, height: 852 },
  { src: "/assets/home/behind-head/pencil/2.webp", width: 460, height: 846 },
  { src: "/assets/home/behind-head/pencil/3.webp", width: 460, height: 462 },
  { src: "/assets/home/behind-head/pencil/4.webp", width: 460, height: 911 },
];
