/**
 * Noah's fifteen password-hand poses, cut from PSDs and registered.
 *
 * GENERATED by tools/password-hand/build_hand.py — do not edit by hand.
 *
 * ALL FIFTEEN SHARE ONE BOX. They were cropped to the union of their own
 * silhouettes after alignment, so drawing every frame at HAND_BOX is what
 * keeps them in register; giving any frame its own rectangle would undo it.
 * The box is in the 1920x1080 artboard units the rest of the site uses, in
 * the position Noah's demo file puts the artwork.
 */

export const HAND_BOX = {"x": 595.3, "y": 105.2, "w": 884.8, "h": 830.2};

/**
 * Where the UNCROPPED 1500x1200 artwork's top-left sits, same units. The
 * fly-in rotates and scales about this point because that is what Noah's
 * demo does (its transform is on the whole artwork, not on a crop), and the
 * two differ by enough — 165 units — to change the
 * shape of the arc.
 */
export const HAND_ART_ORIGIN = { x: 430.1, y: 95.4 };

export const HAND_FRAMES: string[] = [
  "/assets/home/password-hand/1.webp",
  "/assets/home/password-hand/2.webp",
  "/assets/home/password-hand/3.webp",
  "/assets/home/password-hand/4.webp",
  "/assets/home/password-hand/5.webp",
  "/assets/home/password-hand/6.webp",
  "/assets/home/password-hand/7.webp",
  "/assets/home/password-hand/8.webp",
  "/assets/home/password-hand/9.webp",
  "/assets/home/password-hand/10.webp",
  "/assets/home/password-hand/11.webp",
  "/assets/home/password-hand/12.webp",
  "/assets/home/password-hand/13.webp",
  "/assets/home/password-hand/14.webp",
  "/assets/home/password-hand/15.webp",
];

/** Natural pixel size of every frame, for next/image. */
export const HAND_PIXELS = { width: 1200, height: 1126 };
