/**
 * Noah's clay arrows for the résumé card, cut out of one photograph.
 *
 * GENERATED by tools/resume-arrows/build_arrows.py — do not edit by hand.
 *
 * EVERY ARROW POINTS RIGHT in its own artwork, whatever direction it was
 * lying in when photographed. Aiming one is therefore just a rotation to the
 * bearing of its target, with no per-arrow offset to look up.
 */

export type ResumeArrow = {
  src: string;
  colour: "red" | "blue" | "yellow";
  width: number;
  height: number;
};

export const RESUME_ARROWS: ResumeArrow[] = [
  { src: "/assets/home/resume-arrows/1.webp", colour: "red", width: 420, height: 382 },
  { src: "/assets/home/resume-arrows/2.webp", colour: "red", width: 420, height: 208 },
  { src: "/assets/home/resume-arrows/3.webp", colour: "blue", width: 420, height: 283 },
  { src: "/assets/home/resume-arrows/4.webp", colour: "blue", width: 420, height: 451 },
  { src: "/assets/home/resume-arrows/5.webp", colour: "yellow", width: 420, height: 216 },
];
